### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by iaoiui**

### CODE REVIEW

**Comment by aalonsog** [comment]
Please, could you explain what you are proposing/fixing with this PR?

**Comment by iaoiui** [comment]
Hi aalonsog.
I'm proposing following:
- "typo"  9251e414f2073729b65f3eae9e2c3b04e8add8e5
- "Fixing lint error"  370a4d7
- "Incorrect test case" ed44346

I found typo and commit it as  9251e414f2073729b65f3eae9e2c3b04e8add8e5.
Then  I was aware the CI test failed. 
CI test displayed some  lint errors , so I fixed it as 370a4d7.
After fixing lint errors, I found incorrect test case so I also fixed it as ed44346.

Thanks.

**Comment by jason-fox** [comment]
There is a large overlap between this PR and #78. I've **relaxed** the Linting Rule there to allow for `snake_case_variables`, which should remove the need for the _fixing lint error_ change - I also discovered and fixed the unnecessary variables.

The typo `us=>as` does need to be fixed at some point, but could be subsumed into #61 which also adds a simple spell check. @iaoiui - could you add a review on that PR and mark the typos as to be done there so this can be done in a single PR.

The most interesting part of the PR is the change of the hard-coded `/version` string - also required in #78 - @aalonsog , @apozohue10 - why has the URL for the heartbeat been changed? Does this mean that there is a version of Keyrock with the old `/v3...` endpoint out here which will no longer work. Should the `/v3...` endpoint be re-added back in (as a proxy for `/version`)

**Comment by apozohue10** [comment]
Hi @jason-fox and @iaoiui,

Currently, new versions of pep proxy work with the new keyrock (based on node). Previously the endpoint v3 was maintained for compatibilities between the different versions, but I think it makes more sense that if a developer uses an old release of Keyrock also use an old release of Pep Proxy. 
Therefore I don't see any problem in changing the heartbeat URL for future versions of the pep Proxy as @iaoiui has proposed.

We will merge first #78 before this one.

**Comment by apozohue10** [comment]
Hi @iaoiui 

If you could resolved conflicts, we will merge to add changes.

**Comment by jason-fox** [comment]
@iaoiui wrote:

> I'm proposing following:
> 
> * "typo"  [9251e41](https://github.com/ging/fiware-pep-proxy/commit/9251e414f2073729b65f3eae9e2c3b04e8add8e5)
> * "Fixing lint error"  [370a4d7](https://github.com/ging/fiware-pep-proxy/commit/370a4d7f2b995835dbbf4410962adff69eb26dba)
> * "Incorrect test case" [ed44346](https://github.com/ging/fiware-pep-proxy/commit/ed4434635919639d956d49b5a7b96fb7585877b6)

I think it is just the typo that is outstanding. The lint error has been taken care of by relaxing the rules.
I'm not sure of the current state of the test - but I think it has been covered with the merge of #78 - could you confirm.

**Pull request merged**
