### PR TITLE
Format and lint Markdown text files

### PR DESCRIPTION
**Pull request by jason-fox**
@aalonsog @apozohue10 

This PR adds Husky to the existing Prettier set-up so  Markdown files are also auto formatted on commit using husky so no 💩 gets back into the codebase.

Textlint is checking the markdown files - it does find false positives though - especially for terminology.

Try running the following:

```
npm install
npm run prettier:text
npm run lint:text
```

for the various options

### CODE REVIEW

**Comment by aalonsog** [comment]
Hi Jason, apologies for the delay. Could you update the PR for being able to merge it? Thanks!

**Comment by jason-fox** [comment]
It would be better to process #78 first, then I can rebase this one as it is smaller

**Comment by apozohue10** [comment]
We have merged #78 before as you suggested. Could you resolve the conflicts? so that we could merged this also too.

**Comment by jason-fox** [comment]
@apozohue10 @aalonsog   this PR has been rebased and is ready for review

**Comment by apozohue10** [comment]
Merged!

**Pull request merged**
