### PR TITLE
Feature/dependencies

### PR DESCRIPTION
**Pull request by jason-fox**
Missing code lint - completes #105

### CODE REVIEW

**Comment by apozohue10** [comment]
Sorry, It was my fault merging quickly last PR

**Comment by jason-fox** [comment]
@apozohue10 - it's not your fault - you are simply too efficient.

**Comment by apozohue10** [comment]
Is this PR prepared to be merged?
If so, I will accept it and generate the new release

**Comment by jason-fox** [comment]
@apozohue10 - Yes, please merge and test. You'll need to check that:

- Docker build works
- Docker secrets work.

They *were* working on the branch before merge - I can't vouch for the other changes you have merged though.

**Comment by jason-fox** [comment]
@apozohue10 - I've been testing this Dockerized locally and the `async` library is both unnecessary and problematic. I have replaced it with the start-up code _"stolen"_ from Keyrock  d854782 and it works fine for me now.  

I'm not sure why `async` was added in the first place when `setTimeout()` works just as well, seems like unnecessary bloat to me.

**Comment by apozohue10** [comment]
@jason-fox Yes, I think if you can code something without relying on a library is better (unless It is something difficult). If you are interested, yesterday, I tested the PR and I had to turn the function "retryCheck" into an asynchronous function in order to run the PEP Proxy.

Anyways, setTimeout works perfectly. I am going to merge the PR.

Thank you!

**Pull request merged**
